apiVersion: apps/v1
kind: Deployment
metadata:
  name: AksApplication-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AksApplication
  template:
    metadata:
      labels:
        app: AksApplication
    spec:
      containers:
      - name: AksApplication
        image: acrsample12.azurecr.io/reddivaripriyanka/sampleappforaks:#{Build.BuildId}#
        ports:
        - containerPort: 80
        env:
          - name: PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      imagePullSecrets:
      - name: priyankaaks
---
apiVersion: v1
kind: Service
metadata:
  name: AksApplication
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AksApplication
